Repository caris-events/tunalog, pull requests merged in 2024-09, with the labels that each got.

#17 feat(docker): make blog data in a separate folder
  Dockerfile
Labels: 💡 Improvement, 🔌 Build Tools

#20 feat: Add Simplified Chinese support
  entity/entity.go
  system/locales/zh-cn.json
  system/themes/default/locales/zh-cn.json
Labels: 🎨 Frontend

#22 feat: Add sitemap.xml endpoint for SEO optimization #1
  handler/handler.go
  handler/index_sitemap.go
  handler/index_sitemap_test.go
Labels: ✨ New Feature
